[project]
name = "carbon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
host = [
    "aiosqlite>=0.21.0",
]
client = [
    "nanoid>=2.0.0",
]
